# Generated by Django 3.1.7 on 2021-02-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('WorkstationId', models.AutoField(primary_key=True, serialize=False)),
                ('Xposition', models.IntegerField()),
                ('Yposition', models.IntegerField()),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
    ]
